name: CI-CD

on: 
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main 

jobs:
  my_test:
    runs-on: ubuntu-latest

    steps:  
    - name: pwd
      run : pwd
      
    - name: update
      run : sudo apt update
      
    - name: Git clone
      uses: actions/checkout@v1 
      
    - name: npm install
      run : npm install
     
    - name: Node.js
      run : sudo apt install nodejs
      
    - name: Gatsby install
      run : npm install -g gatsby-cli
    
    - name: Gatsby build 
      run : gatsby build
      
    - name: Configure my AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id    :  ${{ secrets.MY_AWS_ACCESS_KEY }}
        aws-secret-access-key:  ${{ secrets.MY_AWS_SECRET_KEY }}
        aws-region           :  eu-north-1
    
