name: CI-CD

on: 
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  my_test:
    runs-on: ubuntu-latest

    steps:
    - name: Git clone
      uses: actions/checkout@v1 
    
    - name: Execute few commands
      run : |
        sudo apt update
        sudo apt install curl
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
        source ~/.bashrc
        nvm install v16.12.0

    - name: List current folder
      run : ls -la 
  
    
