name: CI-CD

on: 
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  my_test:
    runs-on: ubuntu-latest

    steps:
    - name: Git clone
      uses: actions/checkout@v1 
    
    - name: Execute few commands
      run : |
        sudo nvm -v

    - name: List current folder
      run : ls -la 
  
    
